### ISSUE TITLE
Something about the version of tsdb module

### ISSUE THREAD

**Issue by Fragmentszz** [XLI-2020/MPIN#1]
Hi! Thank you for your outstanding contribution!

Upon attempting to replicate the code, I used the command ```pip install -r requirements.txt```. However, due to the rapid updates of the ```tsdb``` module, the installed version was 0.6.2, which is not compatible with the version required by your code. After numerous attempts, I discovered that ```tsdb==0.0.3``` may be the appropriate version.

Could you please update the ```requirements.txt``` file to specify the exact versions of the Python modules? I believe this will greatly facilitate the work of other researchers. Thank you!

**Comment by XLI-2020** [comment]
Thank you for your pointing out this issue! I have added the information of the versions that I used.
